apiVersion: v1
kind: Service
metadata:
  name: azilgateway-np-srv
spec:
    type: NodePort
    selector:
        app: azilgateway
    ports:
        - name: azilgateway-service
          protocol: TCP
          port: 8082
          targetPort: 8080