apiVersion: v1
kind: Service
metadata:
  name: azilauth-np-srv
spec:
    type: NodePort
    selector:
        app: azilauth
    ports:
        - name: azilauth-service
          protocol: TCP
          port: 8080
          targetPort: 8080