apiVersion: v1
kind: Service
metadata:
  name: azilanimals-np-srv
spec:
    type: NodePort
    selector:
        app: azilanimals
    ports:
        - name: azilanimals-service
          protocol: TCP
          port: 8081
          targetPort: 8080