apiVersion: apps/v1
kind: Deployment
metadata:
  name: azilanimals-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azilanimals
  template:
    metadata:
      labels:
        app: azilanimals
    spec:
      containers:
        - name: azilanimals
          image: azilanimals:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=postgres;Port=5432;Database=azil_animals;User Id=admin;Password=admin"
            - name: MessageBroker__HostName
              value: rabbitmq-srv
            - name: MessageBroker__Port
              value: "5672"
            - name: MessageBroker__Username
              value: guest
            - name: MessageBroker__Password
              value: guest
