apiVersion: apps/v1
kind: Deployment
metadata:
  name: azilauth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azilauth
  template:
    metadata:
      labels:
        app: azilauth
    spec:
      containers:
        - name: azilauth
          image: azilauthorization:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=postgres;Port=5432;Database=azil_users;User Id=admin;Password=admin"
