apiVersion: apps/v1
kind: Deployment
metadata:
  name: azilgateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azilgateway
  template:
    metadata:
      labels:
        app: azilgateway
    spec:
      containers:
      - name: azilgateway
        image: azilgateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
        env:
        - name: Urls__Authorization
          value: "http://azilauth-np-srv:8080/api/Auth"
        - name: Urls__Animal
          value: "http://azilanimals-np-srv:8081/api/Animal"
        - name: Urls__AnimalUser
          value: "http://azilgo-np-srv:8082"
