apiVersion: apps/v1
kind: Deployment
metadata:
  name: azilgo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azilgo
  template:
    metadata:
      labels:
        app: azilgo
    spec:
      containers:
        - name: azilgo
          image: azilgo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
          env:
            - name: MONGOURI
              value: "mongodb://mongodb-service:27017"
            