apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 5432
                  env:
                    - name: POSTGRES_USER
                      value: admin
                    - name: POSTGRES_PASSWORD
                      value: admin
                    - name: POSTGRES_DB
                      value: azil.users
                  volumeMounts:
                    - mountPath: /var/lib/postgresql/data
                      name: azil-users-storage
            volumes:
                - name: azil-users-storage
                  persistentVolumeClaim:
                    claimName: postgres-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
    type: ClusterIP
    selector:
        app: postgres
    ports:
        - name: postgres
          protocol: TCP
          port: 5432
          targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
spec:
    type: LoadBalancer
    selector:
        app: postgres
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432          