# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#         - name: postgres
#           image: postgres:16
#           imagePullPolicy: "IfNotPresent"
#           ports:
#             - containerPort: 5432
#           envFrom:
#             - configMapRef:
#                 name: postgres-config
#           volumeMounts:
#             - mountPath: /var/lib/postgresql/data
#               name: postgredb
#       volumes:
#         - name: postgredb
#           persistentVolumeClaim:
#             claimName: postgres-pv-claim

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb 
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
      volumes:
        - name: postgresdb 
          persistentVolumeClaim:
            claimName: postgres-pv-claim